enum ServerStatuses {
  SUCCES = 'SUCCES',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  UNAUTHORIZED = 'UNAUTHORIZED',

  NO_STATUS = 'NO_STATUS',
}

export { ServerStatuses }
